### ISSUE TITLE
Add "release" action on git tag

### ISSUE THREAD

**Issue by ronaldtse** [actions-mn/cli#7]

**Comment by CAMOBAP** [comment]
https://github.com/metanorma/ci/blob/main/.github/workflows/ghpkg-release.yml#L51-L69

**Comment by CAMOBAP** [comment]
@ronaldtse we already have separate release workflows for our ruby gems, so our release workflows looks really clean and compact, like this https://github.com/metanorma/metanorma/blob/main/.github/workflows/release.yml

Maybe you can share more details about what is the idea behind this task

**Comment by CAMOBAP** [comment]
Upd. still make sense to create a separate action for release to reuse in non generic workflows. Will implement it in https://github.com/actions-mn/gem-release

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP , let's close this task. There is another "release" related idea for the metanorma documents but it should be separate thing.
