### ISSUE TITLE
Create separate actions for Metanorma users

### ISSUE THREAD

**Issue by ronaldtse** [actions-mn/cli#9]
I think we should also have separate actions for: 
- "compiling single document" (takes a filename and output name)
- "compiling site" (takes metanorma.yml file path and output name)
- "upload to GH pages"
- "cache fonts"
- "cache metadata"
- "cache relaton"

Then we have one comprehensive one like:
https://github.com/metanorma/S-102-Product-Specification/blob/92f1cc09d6696600a48fd2b45c67171bd92727b4/.github/workflows/generate.yml#L27-L48

i.e. it includes cache, generate site or document (depending on args), uploads to GH pages (depending on args)

**Comment by CAMOBAP** [comment]
> - "compiling single document" (takes a filename and output name)

Done

> - "compiling site" (takes metanorma.yml file path and output name)

Done

> - "upload to GH pages"

I don't see much potential to simplify this, in total we have three actions:
 - actions/configure-pages@v2
 - actions/upload-pages-artifact@v1
 - actions/deploy-pages@v1

And deploy-pages action must be in a separate job

We can kind of simplify it by reusable workflow. Or may unite actions/configure-pages@v2 +  actions/upload-pages-artifact@v1 in a single composite action

> - "cache fonts"
> - "cache metadata"
> - "cache relaton"

I propose to create meta action for those caches 

And then reuse it in https://github.com/actions-mn/setup

----

Once the steps above are done we can simplify https://github.com/metanorma/S-102-Product-Specification/blob/92f1cc09d6696600a48fd2b45c67171bd92727b4/.github/workflows/generate.yml#L27-L48 and use it as a reference

@ronaldtse how do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP thanks. The issue is for the actions stated above, we want GH actions like `https://github.com/actions-mn/{name}`, not `https://github.com/actions-mn/cli/xxxyyy`.

For the caching action (cache fonts + metadata + relaton), can we name it `https://github.com/actions-mn/cache`

For the meta action, can we also name it like `https://github.com/actions-mn/build-and-publish`?

**Comment by CAMOBAP** [comment]
@ronaldtse no problem I kept them inside of single repo just to not bother you with repo creation. But looks like I have access to create a repo.

Agree with your points above let's just confirm the names:
 - [x] https://github.com/actions-mn/compile
 - [x] https://github.com/actions-mn/site-gen
 - [x] https://github.com/actions-mn/cache
 - [x] https://github.com/actions-mn/build-and-publish
 - [x] ~https://github.com/actions-mn/new~ - used only internally so skipping it

@ronaldtse make sense?

**Comment by ronaldtse** [comment]
Agree!

But what is `https://github.com/actions-mn/new` for?

**Comment by CAMOBAP** [comment]
> Agree!
> 
> But what is `https://github.com/actions-mn/new` for?

It's for `metanorma new` to create documents from templates (mn-template-*) probably it was renamed to generate

**Comment by ronaldtse** [comment]
OK, I guess "new" can also work, if people needed to create a new document automatically?

**Comment by CAMOBAP** [comment]
> OK, I guess "new" can also work, if people needed to create a new document automatically?

yep, now I think it probably, makes more sense for us (to test such actions) than for end users

**Comment by CAMOBAP** [comment]
- [x] All actions moved to dedicated repos
 - [x]  https://github.com/metanorma/S-102-Product-Specification/pull/5 - ready for review
 - [x] metanorma/ci repo updated to use new actions
 - [x] cleanup this repo to remove already moved actions from it

**Comment by CAMOBAP** [comment]
Done
